// PLL: 50MHz in, 65.0Mhz out, created in Platform Designer
// Monitor: LG 32LG30-UA 1024x768 @ 60Hz
// connect VGA_CLK to the output of the PLL
// use 8 bits for the rgb values

// top level is vga.v
// the PLL files and sync.v were added to the project in Quartus

module vga(CLOCK_50, VGA_HS, VGA_VS, VGA_R, VGA_G, VGA_B, VGA_SYNC, VGA_BLANK, VGA_CLK, KEY, SW);

   input CLOCK_50; //50Mhz clock on the DE2-115
   input [3:0] KEY; //The 4 buttons "keys" on the FPGA
   input [17:0] SW; //The 18 switches on the FPGA
   output VGA_HS, VGA_VS, VGA_SYNC, VGA_BLANK, VGA_CLK; //VGA Synchronization and clock
   output [7:0] VGA_R, VGA_G, VGA_B; //8 bit Red, Green, Blue outputs
   
   wire vgaclk;
   reg reset = 0;
   
   sync S0 (.CLK(vgaclk), .HSYNC(VGA_HS), .VSYNC(VGA_VS), .R(VGA_R), .G(VGA_G), .B(VGA_B), .KEY(KEY), .SW(SW)); //mapping the clock, synchronization, colours and buttons and switches for sync

   PLL P0 (.clk_in_clk(CLOCK_50), .reset_reset(reset), .clk_out_clk(vgaclk)); //mapping the in, reset and out for the pll

   assign VGA_SYNC = 1; //default value
   assign VGA_BLANK = 1; //default value
   assign VGA_CLK = vgaclk; //clock set to frequency generated by pll

endmodule

