
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DFT_Network(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		     [1:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
/* For driving butterfly_sum */
reg [73:0] test_i_A         = 74'h0_00_00_80_00_00_00_08_00_00;
reg [73:0] test_i_B         = 74'h0_00_01_80_00_00_00_10_00_00;
reg [73:0] test_i_twiddle   = 74'h0_00_00_80_00_00_00_00_00_00;
wire [73:0] test_o_A, test_o_B;          

//=======================================================
//  Structural coding
//=======================================================
butterfly_sum MY_MOD 
    (
        .i_CLK(CLOCK_50),
        .i_RST(~KEY[0]),
        .i_A(test_i_A),
        .i_B(test_i_B),
        .i_twiddle(test_i_twiddle),
        .o_A(test_o_A),
        .o_B(test_o_B)
    );

endmodule
